### ISSUE TITLE
 panic: runtime error: slice bounds out of range [:13] with capacity 1

### ISSUE THREAD

**Issue by petr-balogh** [RedHatQE/tfacon#27]
**Describe the bug**
Recently we started see this kind of issues:
2022-07-08 01:31:42  Initializing Defect Types...
2022-07-08 01:31:43  panic: runtime error: slice bounds out of range [:13] with capacity 1
2022-07-08 01:31:43  
2022-07-08 01:31:43  goroutine 27 [running]:
2022-07-08 01:31:43  github.com/RedHatQE/tfacon/connectors.processREReturnedText(0x0, 0x0, 0x8db5c3, 0x6)
2022-07-08 01:31:43  	/home/runner/work/tfacon/tfacon/connectors/rp_connector.go:342 +0x42f
2022-07-08 01:31:43  github.com/RedHatQE/tfacon/connectors.(*RPConnector).GetREResult(0xc0000ee400, 0xc00037794f, 0x26, 0xc00037794f, 0x26)
2022-07-08 01:31:43  	/home/runner/work/tfacon/tfacon/connectors/rp_connector.go:333 +0x271
2022-07-08 01:31:43  github.com/RedHatQE/tfacon/connectors.(*RPConnector).BuildIssueItemHelper(0xc0000ee400, 0xc0001df312, 0x6, 0x101, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2022-07-08 01:31:43  	/home/runner/work/tfacon/tfacon/connectors/rp_connector.go:298 +0x6fd
2022-07-08 01:31:43  github.com/RedHatQE/tfacon/connectors.(*RPConnector).BuildIssueItemConcurrent(0xc0000ee400, 0xc00036c0c0, 0xc00036c120, 0xc000370150, 0xc000320101)
2022-07-08 01:31:43  	/home/runner/work/tfacon/tfacon/connectors/rp_connector.go:369 +0x72
2022-07-08 01:31:43  created by github.com/RedHatQE/tfacon/connectors.(*RPConnector).BuildIssuesConcurrent
2022-07-08 01:31:43  	/home/runner/work/tfacon/tfacon/connectors/rp_connector.go:256 +0x16b

<img width="260" alt="Screen Shot 2022-07-08 at 3 49 08 PM" src="https://user-images.githubusercontent.com/16169617/178004889-74d07f72-f122-4135-aa6f-5c3c4868d4a1.png">

I see there is big timeframe for those error, so not sure if it might be related to model restart?
Few links:
https://url.corp.redhat.com/91e61ed
https://url.corp.redhat.com/45daed0
https://url.corp.redhat.com/e403ff3

**To Reproduce**
When I tried to re-produce now by re-triggering one of the failed job it passed ok. E.g. here:
https://url.corp.redhat.com/9235eae
https://url.corp.redhat.com/2e07e7c

**Expected behavior**
To update the predictions and recommendations

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by JunqiZhang0** [comment]
looking at it

**Comment by yanan-fu** [comment]
I hit this same issue if run `tfacon` with `-r`:
```
Initializing Defect Types...
panic: runtime error: slice bounds out of range [:13] with capacity 1

goroutine 13 [running]:
github.com/RedHatQE/tfacon/connectors.processREReturnedText(0x0, 0x0, 0x8db5c3, 0x6)
	/home/runner/work/tfacon/tfacon/connectors/rp_connector.go:342 +0x42f
github.com/RedHatQE/tfacon/connectors.(*RPConnector).GetREResult(0xc000192400, 0xc00032f24d, 0xc, 0xc00032f24d, 0xc)
	/home/runner/work/tfacon/tfacon/connectors/rp_connector.go:333 +0x271
github.com/RedHatQE/tfacon/connectors.(*RPConnector).BuildIssueItemHelper(0xc000192400, 0xc0000b46f2, 0x4, 0x101, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/runner/work/tfacon/tfacon/connectors/rp_connector.go:298 +0x6fd
github.com/RedHatQE/tfacon/connectors.(*RPConnector).BuildIssueItemConcurrent(0xc000192400, 0xc00007f200, 0xc00007f260, 0xc000364cb0, 0xc000400101)
	/home/runner/work/tfacon/tfacon/connectors/rp_connector.go:369 +0x72
created by github.com/RedHatQE/tfacon/connectors.(*RPConnector).BuildIssuesConcurrent
	/home/runner/work/tfacon/tfacon/connectors/rp_connector.go:256 +0x16b
```

Run tfacon without `-r` looks normal.

**Comment by petr-balogh** [comment]
Hit again here:
https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-tfac/1630/console

@JunqiZhang0 any update here please?

**Comment by petr-balogh** [comment]
Next reproduce:
https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-tfac/1646//console
:(

**Comment by lukas-bednar** [comment]
We are facing this problem as well.

**Comment by JunqiZhang0** [comment]
Fixing this

**Comment by JunqiZhang0** [comment]
fixed by the latest release
