### ISSUE TITLE
When the recommendation engine is down we get panic without a clear error message

### ISSUE THREAD

**Issue by lukas-bednar** [RedHatQE/tfacon#28]
**Describe the bug**

**When the recommendation engine is down** we get panic without a clear error message.
We get `panic: http handler request exception, status code is:404, err is %!w(<nil>)` .
I would expect to see which server we have a problem with ... it could be the report portal, or recommendation engine, or the classifier ...
I had to dive into the code to see which endpoint is not responding correctly...

```
11:57:41  + tfacon run --verbose --re --re-url https://dave.corp.redhat.com:443/models/61b8d1acfa9c3f1c2fd2c914/latest/model --launch-id 1127
11:57:41  --------------------------------------------------
11:57:41  tfacon  1.0.3
11:57:41  Copyright (C) 2021, Red Hat, Inc.
11:57:41  -------------------------------------------------
11:57:41  
11:57:41  
11:57:41  Initializing Defect Types...
11:57:41  panic: http handler request exception, status code is:404, err is %!w(<nil>)
11:57:41  
11:57:41  
11:57:41  goroutine 139 [running]:
11:57:41  github.com/RedHatQE/tfacon/connectors.(*RPConnector).GetPrediction(0xc000020500, 0xc00044e812, 0x6, 0xc00044e812, 0x6, 0xc0000315c8, 0x3, 0xc0004f0600, 0x17f, 0x0, ...)
11:57:41  	/home/runner/work/tfacon/tfacon/connectors/rp_connector.go:426 +0x30b
11:57:41  github.com/RedHatQE/tfacon/connectors.(*RPConnector).BuildIssueItemHelper(0xc000020500, 0xc00044e812, 0x6, 0x101, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
11:57:41  	/home/runner/work/tfacon/tfacon/connectors/rp_connector.go:281 +0x1c5
11:57:41  github.com/RedHatQE/tfacon/connectors.(*RPConnector).BuildIssueItemConcurrent(0xc000020500, 0xc0002b9b00, 0xc0002b9b60, 0xc000352b00, 0xc0002e0101)
11:57:41  	/home/runner/work/tfacon/tfacon/connectors/rp_connector.go:369 +0x72
11:57:41  created by github.com/RedHatQE/tfacon/connectors.(*RPConnector).BuildIssuesConcurrent
11:57:41  	/home/runner/work/tfacon/tfacon/connectors/rp_connector.go:256 +0x16b
```

**To Reproduce**
While the recommendation engine is down, try to run tfacon.
tfacon run --verbose --re --re-url https://dave.corp.redhat.com:443/models/61b8d1acfa9c3f1c2fd2c914/latest/model --launch-id 1127

**Expected behavior**

I want to see something like:
```
panic: Recommendation engine can not be reached:  status code is:404
```

The same applies to the TFA, and report portal endpoints.

**Comment by petr-balogh** [comment]
Today we see other error code:

```
2022-07-28 11:23:35  + tfacon run --re --re-url [https://dave.corp.redhat.com:443/models/61b8d1acfa9c3f1c2fd2c914/latest/model](https://dave.corp.redhat.com/models/61b8d1acfa9c3f1c2fd2c914/latest/model) --launch-id 4041
2022-07-28 11:23:35  --------------------------------------------------
2022-07-28 11:23:35  tfacon  1.0.3
2022-07-28 11:23:35  Copyright (C) 2021, Red Hat, Inc.
2022-07-28 11:23:35  -------------------------------------------------
2022-07-28 11:23:35  
2022-07-28 11:23:35  
2022-07-28 11:23:35  Initializing Defect Types...
2022-07-28 11:23:36  panic: http handler request exception, status code is:413, err is %!w(<nil>)
2022-07-28 11:23:36  
2022-07-28 11:23:36  
2022-07-28 11:23:36  goroutine 48 [running]:
2022-07-28 11:23:36  github.com/RedHatQE/tfacon/connectors.(*RPConnector).GetPrediction(0xc000164400, 0xc0005635fa, 0x6, 0xc0005635fa, 0x6, 0xc0000315b8, 0x3, 0xc001b64000, 0x9d9777, 0x0, ...)
2022-07-28 11:23:36  	/home/runner/work/tfacon/tfacon/connectors/rp_connector.go:426 +0x30b
2022-07-28 11:23:36  github.com/RedHatQE/tfacon/connectors.(*RPConnector).BuildIssueItemHelper(0xc000164400, 0xc0005635fa, 0x6, 0x101, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2022-07-28 11:23:36  	/home/runner/work/tfacon/tfacon/connectors/rp_connector.go:281 +0x1c5
2022-07-28 11:23:36  github.com/RedHatQE/tfacon/connectors.(*RPConnector).BuildIssueItemConcurrent(0xc000164400, 0xc00055c120, 0xc00055c180, 0xc00057c000, 0xc000560101)
2022-07-28 11:23:36  	/home/runner/work/tfacon/tfacon/connectors/rp_connector.go:369 +0x72
2022-07-28 11:23:36  created by github.com/RedHatQE/tfacon/connectors.(*RPConnector).BuildIssuesConcurrent
2022-07-28 11:23:36  	/home/runner/work/tfacon/tfacon/connectors/rp_connector.go:256 +0x16b
```

https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-tfac/1483/console

@JunqiZhang0 can you please take a look?

**Comment by JunqiZhang0** [comment]
Looking at it
